### ISSUE TITLE
Will the code be released in the future?

### ISSUE THREAD

**Issue by KaninchenM** [Artisense-ai/GN-Net-Benchmark#1]
Will the code be released later? Especially the code of network structure and training? Thank you.

**Comment by lukasvst** [comment]
Unfortunately we were not allowed to open source the training or inference code of GN-Net. In case you decide to reimplement it in the future and have any questions please write me an e-mail, I will be happy to answer any questions regarding it.

**Comment by KaninchenM** [comment]
> Unfortunately we were not allowed to open source the training or inference code of GN-Net. In case you decide to reimplement it in the future and have any questions please write me an e-mail, I will be happy to answer any questions regarding it.

OK, thank you for your reply,
